FROM luke/ubuntu
MAINTAINER luke <461025755@qq.com>

WORKDIR /src

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing  nginx-full

RUN groupmod --gid 1000 www-data && usermod --uid 1000 --gid 1000 www-data
RUN apt-get autoclean \
    && apt-get autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]